version: "3"
services:
  app:
    image: pkpudev/apache-yii2
    container_name: stddev-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  db:
    image: pkpudev/postgres-yii2
    container_name: stddev-db
    environment:
      - POSTGRES_USER=standard
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pkpu_db
    ports:
      - "2345:5432"