<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;

/**
 * This is the base-model class for table "public.com_branch".
 *
 * @property integer $id
 * @property string $branch_name
 * @property string $location_code
 * @property string $location
 * @property integer $parent_id
 * @property string $kode_cabang
 * @property string $branch_address
 * @property string $branch_phone
 * @property string $branch_fax
 * @property string $branch_bankaccount1
 * @property string $branch_bankaccount2
 * @property integer $php_sort
 * @property integer $taxonomy_id
 * @property string $created_stamp
 * @property string $updated_stamp
 * @property integer $company_id
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $aliasModel
 */
abstract class Branch extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'public.com_branch';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'php_sort', 'taxonomy_id', 'company_id'], 'integer'],
            [['created_stamp', 'updated_stamp'], 'safe'],
            [['branch_name', 'location', 'branch_phone'], 'string', 'max' => 50],
            [['location_code'], 'string', 'max' => 10],
            [['kode_cabang'], 'string', 'max' => 20],
            [['branch_address'], 'string', 'max' => 400],
            [['branch_fax'], 'string', 'max' => 30],
            [['branch_bankaccount1', 'branch_bankaccount2'], 'string', 'max' => 200]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'branch_name' => 'Branch Name',
            'location_code' => 'Location Code',
            'location' => 'Location',
            'parent_id' => 'Parent ID',
            'kode_cabang' => 'Kode Cabang',
            'branch_address' => 'Branch Address',
            'branch_phone' => 'Branch Phone',
            'branch_fax' => 'Branch Fax',
            'branch_bankaccount1' => 'Branch Bankaccount1',
            'branch_bankaccount2' => 'Branch Bankaccount2',
            'php_sort' => 'Php Sort',
            'taxonomy_id' => 'Taxonomy ID',
            'created_stamp' => 'Created Stamp',
            'created_by' => 'Created By',
            'updated_stamp' => 'Updated Stamp',
            'updated_by' => 'Updated By',
            'company_id' => 'Company ID',
        ];
    }




}
