<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sdm_employee".
 *
 * @property integer $id
 * @property string $user_name
 * @property string $passwd
 * @property string $email
 * @property string $full_name
 * @property integer $user_status
 * @property string $_history
 * @property integer $phone_id
 * @property string $register_date
 * @property integer $branch_id
 * @property string $guid
 * @property integer $is_new_task
 * @property string $activkey
 * @property integer $parent_alias_id
 * @property integer $company_id
 * @property string $auth_key
 * @property integer $expired_key
 * @property string $donor_no
 * @property string $address
 * @property string $postal_code
 * @property integer $location_id
 * @property string $npwp_no
 * @property string $npwz_no
 * @property integer $is_donor
 * @property integer $country_id
 * @property integer $fax_id
 * @property integer $bank_account_id
 * @property integer $marketer_id
 * @property integer $donor_type_id
 * @property string $text_searchable
 * @property string $last_login
 * @property integer $is_valid
 * @property string $donor_no_old
 * @property string $website
 * @property integer $phone_mark
 * @property integer $mail_mark
 * @property string $updated_validity
 * @property string $note
 * @property string $alias_name
 * @property integer $created_by
 * @property string $created_stamp
 * @property integer $updated_by
 * @property string $updated_stamp
 * @property integer $is_new
 * @property integer $has_idcard
 * @property integer $remainder_date
 * @property string $remainder_message
 * @property string $address_full
 * @property string $phone_no_full
 * @property string $blood_type
 * @property string $data_source
 * @property integer $donor_company_id
 * @property string $birth_place
 * @property string $birth_date
 * @property integer $sex
 * @property string $starting_date
 * @property string $ending_date
 * @property integer $is_employee
 * @property integer $position_id
 * @property integer $is_marketer
 * @property integer $employee_type_id
 * @property string $permanent_address
 * @property string $current_phone_no
 * @property string $permanent_phone_no
 * @property string $identity_no
 * @property integer $marital_status
 * @property string $user_image
 * @property integer $branch_id_financial
 * @property integer $is_external_orphan_admin
 * @property string $nip
 *
 * @property \app\models\Asset[] $assets
 * @property \app\models\Asset[] $assets0
 * @property \app\models\AssetUsage[] $assetUsages
 * @property \app\models\AssetUsage[] $assetUsages0
 * @property \app\models\AssetUsage[] $assetUsages1
 * @property \app\models\AssetUsage[] $assetUsages2
 * @property \app\models\Maintenance[] $maintenances
 * @property \app\models\Maintenance[] $maintenances0
 * @property \app\models\Maintenance[] $maintenances1
 * @property \app\models\Maintenance[] $maintenances2
 * @property \app\models\MaintenanceType[] $maintenanceTypes
 * @property \app\models\Request[] $requests
 * @property \app\models\Request[] $requests0
 * @property \app\models\Request[] $requests1
 * @property \app\models\Request[] $requests2
 * @property \app\models\RequestHistory[] $requestHistories
 * @property \app\models\TransportUsage[] $transportUsages
 * @property \app\models\TransportUsage[] $transportUsages0
 * @property \app\models\Userinfo $userinfo
 * @property \app\models\Bsc[] $bscs
 * @property \app\models\BudgetHistory[] $budgetHistories
 * @property \app\models\Creator[] $creators
 * @property \app\models\KpiHistory[] $kpiHistories
 * @property \app\models\StrategicInitiativesHistory[] $strategicInitiativesHistories
 * @property \app\models\StrategicObjectivesHistory[] $strategicObjectivesHistories
 * @property \app\models\Payment[] $payments
 * @property \app\models\Payment[] $payments0
 * @property \app\models\Procurement[] $procurements
 * @property \app\models\Procurement[] $procurements0
 * @property \app\models\Procurement[] $procurements1
 * @property \app\models\Procurement[] $procurements2
 * @property \app\models\ProcurementDetail[] $procurementDetails
 * @property \app\models\ProcurementDetail[] $procurementDetails0
 * @property \app\models\CashBank[] $cashBanks
 * @property \app\models\Disbursement[] $disbursements
 * @property \app\models\DisbursementHistory[] $disbursementHistories
 * @property \app\models\PettyCash[] $pettyCashes
 * @property \app\models\Comments[] $comments
 * @property \app\models\Thread[] $threads
 * @property \app\models\Allowance[] $allowances
 * @property \app\models\AllowanceSubmit[] $allowanceSubmits
 * @property \app\models\AmilEmployee[] $amilEmployees
 * @property \app\models\Bpjs $bpjs
 * @property \app\models\CooperativeMembers[] $cooperativeMembers
 * @property \app\models\DebtTransaction[] $debtTransactions
 * @property \app\models\EmployeeNip $employeeNip
 * @property \app\models\EmployeeAccount[] $employeeAccounts
 * @property \app\models\EmployeeCooperative[] $employeeCooperatives
 * @property \app\models\EmployeeDebt[] $employeeDebts
 * @property \app\models\LatenessResume[] $latenessResumes
 * @property \app\models\Leave[] $leaves
 * @property \app\models\LeaveRecord[] $leaveRecords
 * @property \app\models\Overtime[] $overtimes
 * @property \app\models\OvertimeResume[] $overtimeResumes
 * @property \app\models\PayTakehomeMaster[] $payTakehomeMasters
 * @property \app\models\Payroll[] $payrolls
 * @property \app\models\ThpRecord[] $thpRecords
 * @property \app\models\UpdateProfileLog[] $updateProfileLogs
 * @property \app\models\UpdateProfileLog[] $updateProfileLogs0
 * @property \app\models\Accountrecovery[] $accountrecoveries
 * @property \app\models\Usergrouphead[] $usergroupheads
 * @property \app\models\Usergroup[] $groupnames
 * @property \app\models\Usergroupmember[] $usergroupmembers
 * @property \app\models\Usergrouphead[] $heads
 * @property \app\models\ApplicationHistory[] $applicationHistories
 * @property \app\models\GroupMember[] $groupMembers
 * @property \app\models\GroupName[] $groupNames
 * @property \app\models\MutabaahReport[] $mutabaahReports
 * @property \app\models\MutabaahTarget[] $mutabaahTargets
 * @property \app\models\DonationItemHistory[] $donationItemHistories
 * @property \app\models\Ipp[] $ipps
 * @property \app\models\IppMaster[] $ippMasters
 * @property \app\models\Person $person
 * @property \app\models\SysMailRecipient[] $sysMailRecipients
 * @property \app\models\PhoneSellingDonor[] $phoneSellingDonors
 * @property \app\models\GrwTask[] $grwTasks
 * @property \app\models\GrwTask[] $grwTasks0
 * @property \app\models\PhpDonationPreference[] $phpDonationPreferences
 * @property \app\models\ComBranch $branch
 * @property \app\models\ComBranch $branchIdFinancial
 * @property \app\models\Company $company
 * @property \app\models\EmployeeType $employeeType
 * @property \app\models\EmployeeExpertise[] $employeeExpertises
 * @property \app\models\EmployeeExtended $employeeExtended
 * @property \app\models\PositionHistory[] $positionHistories
 * @property string $aliasModel
 */
abstract class Employee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sdm_employee';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_status', 'phone_id', 'branch_id', 'is_new_task', 'parent_alias_id', 'company_id', 'expired_key', 'location_id', 'is_donor', 'country_id', 'fax_id', 'bank_account_id', 'marketer_id', 'donor_type_id', 'is_valid', 'phone_mark', 'mail_mark', 'created_by', 'updated_by', 'is_new', 'has_idcard', 'remainder_date', 'donor_company_id', 'sex', 'is_employee', 'position_id', 'is_marketer', 'employee_type_id', 'marital_status', 'branch_id_financial', 'is_external_orphan_admin'], 'integer'],
            [['_history', 'address', 'text_searchable', 'note', 'address_full', 'phone_no_full', 'permanent_address'], 'string'],
            [['register_date', 'last_login', 'updated_validity', 'created_stamp', 'updated_stamp', 'birth_date', 'starting_date', 'ending_date'], 'safe'],
            [['user_name', 'guid', 'activkey', 'auth_key', 'birth_place'], 'string', 'max' => 40],
            [['passwd', 'email', 'data_source', 'user_image'], 'string', 'max' => 100],
            [['full_name'], 'string', 'max' => 150],
            [['donor_no'], 'string', 'max' => 20],
            [['postal_code'], 'string', 'max' => 10],
            [['npwp_no', 'npwz_no'], 'string', 'max' => 24],
            [['donor_no_old', 'current_phone_no', 'permanent_phone_no'], 'string', 'max' => 15],
            [['website'], 'string', 'max' => 50],
            [['alias_name', 'identity_no'], 'string', 'max' => 30],
            [['remainder_message'], 'string', 'max' => 160],
            [['blood_type'], 'string', 'max' => 2],
            [['nip'], 'string', 'max' => 12],
            [['donor_no'], 'unique'],
            [['email'], 'unique'],
            [['nip'], 'unique'],
            [['user_name'], 'unique'],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
            [['branch_id_financial'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id_financial' => 'id']],
            [['company_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Company::className(), 'targetAttribute' => ['company_id' => 'id']],
            [['employee_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\EmployeeType::className(), 'targetAttribute' => ['employee_type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_name' => 'User Name',
            'passwd' => 'Passwd',
            'email' => 'Email',
            'full_name' => 'Full Name',
            'user_status' => 'User Status',
            '_history' => 'History',
            'phone_id' => 'Phone ID',
            'register_date' => 'Register Date',
            'branch_id' => 'Branch ID',
            'guid' => 'Guid',
            'is_new_task' => 'Is New Task',
            'activkey' => 'Activkey',
            'parent_alias_id' => 'Parent Alias ID',
            'company_id' => 'Company ID',
            'auth_key' => 'Auth Key',
            'expired_key' => 'Expired Key',
            'donor_no' => 'Donor No',
            'address' => 'Address',
            'postal_code' => 'Postal Code',
            'location_id' => 'Location ID',
            'npwp_no' => 'Npwp No',
            'npwz_no' => 'Npwz No',
            'is_donor' => 'Is Donor',
            'country_id' => 'Country ID',
            'fax_id' => 'Fax ID',
            'bank_account_id' => 'Bank Account ID',
            'marketer_id' => 'Marketer ID',
            'donor_type_id' => 'Donor Type ID',
            'text_searchable' => 'Text Searchable',
            'last_login' => 'Last Login',
            'is_valid' => 'Is Valid',
            'donor_no_old' => 'Donor No Old',
            'website' => 'Website',
            'phone_mark' => 'Phone Mark',
            'mail_mark' => 'Mail Mark',
            'updated_validity' => 'Updated Validity',
            'note' => 'Note',
            'alias_name' => 'Alias Name',
            'created_by' => 'Created By',
            'created_stamp' => 'Created Stamp',
            'updated_by' => 'Updated By',
            'updated_stamp' => 'Updated Stamp',
            'is_new' => 'Is New',
            'has_idcard' => 'Has Idcard',
            'remainder_date' => 'Remainder Date',
            'remainder_message' => 'Remainder Message',
            'address_full' => 'Address Full',
            'phone_no_full' => 'Phone No Full',
            'blood_type' => 'Blood Type',
            'data_source' => 'Data Source',
            'donor_company_id' => 'Donor Company ID',
            'birth_place' => 'Birth Place',
            'birth_date' => 'Birth Date',
            'sex' => 'Sex',
            'starting_date' => 'Starting Date',
            'ending_date' => 'Ending Date',
            'is_employee' => 'Is Employee',
            'position_id' => 'Position ID',
            'is_marketer' => 'Is Marketer',
            'employee_type_id' => 'Employee Type ID',
            'permanent_address' => 'Permanent Address',
            'current_phone_no' => 'Current Phone No',
            'permanent_phone_no' => 'Permanent Phone No',
            'identity_no' => 'Identity No',
            'marital_status' => 'Marital Status',
            'user_image' => 'User Image',
            'branch_id_financial' => 'Branch Id Financial',
            'is_external_orphan_admin' => 'dipakai DATABASEYATIM',
            'nip' => 'Nip',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'is_external_orphan_admin' => 'dipakai DATABASEYATIM',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssets()
    {
        return $this->hasMany(\app\models\Asset::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssets0()
    {
        return $this->hasMany(\app\models\Asset::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssetUsages()
    {
        return $this->hasMany(\app\models\AssetUsage::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssetUsages0()
    {
        return $this->hasMany(\app\models\AssetUsage::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssetUsages1()
    {
        return $this->hasMany(\app\models\AssetUsage::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssetUsages2()
    {
        return $this->hasMany(\app\models\AssetUsage::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaintenances()
    {
        return $this->hasMany(\app\models\Maintenance::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaintenances0()
    {
        return $this->hasMany(\app\models\Maintenance::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaintenances1()
    {
        return $this->hasMany(\app\models\Maintenance::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaintenances2()
    {
        return $this->hasMany(\app\models\Maintenance::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaintenanceTypes()
    {
        return $this->hasMany(\app\models\MaintenanceType::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests()
    {
        return $this->hasMany(\app\models\Request::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests0()
    {
        return $this->hasMany(\app\models\Request::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests1()
    {
        return $this->hasMany(\app\models\Request::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequests2()
    {
        return $this->hasMany(\app\models\Request::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRequestHistories()
    {
        return $this->hasMany(\app\models\RequestHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransportUsages()
    {
        return $this->hasMany(\app\models\TransportUsage::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransportUsages0()
    {
        return $this->hasMany(\app\models\TransportUsage::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserinfo()
    {
        return $this->hasOne(\app\models\Userinfo::className(), ['sdm_employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBscs()
    {
        return $this->hasMany(\app\models\Bsc::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBudgetHistories()
    {
        return $this->hasMany(\app\models\BudgetHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreators()
    {
        return $this->hasMany(\app\models\Creator::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKpiHistories()
    {
        return $this->hasMany(\app\models\KpiHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStrategicInitiativesHistories()
    {
        return $this->hasMany(\app\models\StrategicInitiativesHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStrategicObjectivesHistories()
    {
        return $this->hasMany(\app\models\StrategicObjectivesHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayments()
    {
        return $this->hasMany(\app\models\Payment::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayments0()
    {
        return $this->hasMany(\app\models\Payment::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurements()
    {
        return $this->hasMany(\app\models\Procurement::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurements0()
    {
        return $this->hasMany(\app\models\Procurement::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurements1()
    {
        return $this->hasMany(\app\models\Procurement::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurements2()
    {
        return $this->hasMany(\app\models\Procurement::className(), ['pic' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurementDetails()
    {
        return $this->hasMany(\app\models\ProcurementDetail::className(), ['created_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProcurementDetails0()
    {
        return $this->hasMany(\app\models\ProcurementDetail::className(), ['updated_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCashBanks()
    {
        return $this->hasMany(\app\models\CashBank::className(), ['pic_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDisbursements()
    {
        return $this->hasMany(\app\models\Disbursement::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDisbursementHistories()
    {
        return $this->hasMany(\app\models\DisbursementHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPettyCashes()
    {
        return $this->hasMany(\app\models\PettyCash::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(\app\models\Comments::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getThreads()
    {
        return $this->hasMany(\app\models\Thread::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowances()
    {
        return $this->hasMany(\app\models\Allowance::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAllowanceSubmits()
    {
        return $this->hasMany(\app\models\AllowanceSubmit::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAmilEmployees()
    {
        return $this->hasMany(\app\models\AmilEmployee::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBpjs()
    {
        return $this->hasOne(\app\models\Bpjs::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCooperativeMembers()
    {
        return $this->hasMany(\app\models\CooperativeMembers::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebtTransactions()
    {
        return $this->hasMany(\app\models\DebtTransaction::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeNip()
    {
        return $this->hasOne(\app\models\EmployeeNip::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeAccounts()
    {
        return $this->hasMany(\app\models\EmployeeAccount::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeCooperatives()
    {
        return $this->hasMany(\app\models\EmployeeCooperative::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeDebts()
    {
        return $this->hasMany(\app\models\EmployeeDebt::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLatenessResumes()
    {
        return $this->hasMany(\app\models\LatenessResume::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaves()
    {
        return $this->hasMany(\app\models\Leave::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLeaveRecords()
    {
        return $this->hasMany(\app\models\LeaveRecord::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOvertimes()
    {
        return $this->hasMany(\app\models\Overtime::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOvertimeResumes()
    {
        return $this->hasMany(\app\models\OvertimeResume::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayTakehomeMasters()
    {
        return $this->hasMany(\app\models\PayTakehomeMaster::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayrolls()
    {
        return $this->hasMany(\app\models\Payroll::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getThpRecords()
    {
        return $this->hasMany(\app\models\ThpRecord::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateProfileLogs()
    {
        return $this->hasMany(\app\models\UpdateProfileLog::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateProfileLogs0()
    {
        return $this->hasMany(\app\models\UpdateProfileLog::className(), ['update_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccountrecoveries()
    {
        return $this->hasMany(\app\models\Accountrecovery::className(), ['email' => 'email']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsergroupheads()
    {
        return $this->hasMany(\app\models\Usergrouphead::className(), ['userid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupnames()
    {
        return $this->hasMany(\app\models\Usergroup::className(), ['name' => 'groupname'])->viaTable('usergrouphead', ['userid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsergroupmembers()
    {
        return $this->hasMany(\app\models\Usergroupmember::className(), ['member' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHeads()
    {
        return $this->hasMany(\app\models\Usergrouphead::className(), ['id' => 'head'])->viaTable('usergroupmember', ['member' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getApplicationHistories()
    {
        return $this->hasMany(\app\models\ApplicationHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupMembers()
    {
        return $this->hasMany(\app\models\GroupMember::className(), ['member_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupNamesAdmin()
    {
        return $this->hasMany(\app\models\GroupName::className(), ['admin' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMutabaahReports()
    {
        return $this->hasMany(\app\models\MutabaahReport::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMutabaahTargets()
    {
        return $this->hasMany(\app\models\MutabaahTarget::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDonationItemHistories()
    {
        return $this->hasMany(\app\models\DonationItemHistory::className(), ['by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIpps()
    {
        return $this->hasMany(\app\models\Ipp::className(), ['marketer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIppMasters()
    {
        return $this->hasMany(\app\models\IppMaster::className(), ['marketer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerson()
    {
        return $this->hasOne(\app\models\Person::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSysMailRecipients()
    {
        return $this->hasMany(\app\models\SysMailRecipient::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhoneSellingDonors()
    {
        return $this->hasMany(\app\models\PhoneSellingDonor::className(), ['calling_by' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrwTasks()
    {
        return $this->hasMany(\app\models\GrwTask::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrwTasks0()
    {
        return $this->hasMany(\app\models\GrwTask::className(), ['assigner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhpDonationPreferences()
    {
        return $this->hasMany(\app\models\PhpDonationPreference::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranchIdFinancial()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id_financial']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::className(), ['id' => 'company_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeType()
    {
        return $this->hasOne(\app\models\EmployeeType::className(), ['id' => 'employee_type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeExpertises()
    {
        return $this->hasMany(\app\models\EmployeeExpertise::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployeeExtended()
    {
        return $this->hasOne(\app\models\EmployeeExtended::className(), ['employee_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPositionHistories()
    {
        return $this->hasMany(\app\models\PositionHistory::className(), ['employee_id' => 'id']);
    }




}
