<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "hrm.vw_position".
 *
 * @property integer $employee_id
 * @property string $full_name
 * @property string $position_name
 * @property string $department
 * @property integer $supposition_id
 * @property string $aliasModel
 */
abstract class VwPosition extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'hrm.vw_position';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if ($plural) {
            return Yii::t('app', 'VwPositions');
        } else {
            return Yii::t('app', 'VwPosition');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['employee_id', 'supposition_id'], 'integer'],
            [['full_name'], 'string', 'max' => 150],
            [['position_name'], 'string', 'max' => 50],
            [['department'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'employee_id' => 'Employee ID',
            'full_name' => 'Full Name',
            'position_name' => 'Position Name',
            'department' => 'Department',
            'supposition_id' => 'Supposition ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'employee_id' => 'Employee Id',
            'full_name' => 'Full Name',
            'position_name' => 'Position Name',
            'department' => 'Department',
            'supposition_id' => 'Supposition Id',
            ]
        );
    }
}
